/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'academic-terms': RouteRecordInfo<'academic-terms', '/academic-terms', Record<never, never>, Record<never, never>>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'class-sections': RouteRecordInfo<'class-sections', '/class-sections', Record<never, never>, Record<never, never>>,
    'classes': RouteRecordInfo<'classes', '/classes', Record<never, never>, Record<never, never>>,
    'classes-id': RouteRecordInfo<'classes-id', '/classes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'courses': RouteRecordInfo<'courses', '/courses', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'dean-dashboard': RouteRecordInfo<'dean-dashboard', '/dean/dashboard', Record<never, never>, Record<never, never>>,
    'dean-surveys': RouteRecordInfo<'dean-surveys', '/dean/surveys', Record<never, never>, Record<never, never>>,
    'dean-surveys-id': RouteRecordInfo<'dean-surveys-id', '/dean/surveys-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'departments': RouteRecordInfo<'departments', '/departments', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'landing': RouteRecordInfo<'landing', '/landing', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pages-authentication-forgot-password-v1': RouteRecordInfo<'pages-authentication-forgot-password-v1', '/pages/authentication/forgot-password-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-forgot-password-v2': RouteRecordInfo<'pages-authentication-forgot-password-v2', '/pages/authentication/forgot-password-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v1': RouteRecordInfo<'pages-authentication-login-v1', '/pages/authentication/login-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v2': RouteRecordInfo<'pages-authentication-login-v2', '/pages/authentication/login-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-multi-steps': RouteRecordInfo<'pages-authentication-register-multi-steps', '/pages/authentication/register-multi-steps', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-v1': RouteRecordInfo<'pages-authentication-register-v1', '/pages/authentication/register-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-v2': RouteRecordInfo<'pages-authentication-register-v2', '/pages/authentication/register-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-reset-password-v1': RouteRecordInfo<'pages-authentication-reset-password-v1', '/pages/authentication/reset-password-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-reset-password-v2': RouteRecordInfo<'pages-authentication-reset-password-v2', '/pages/authentication/reset-password-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-two-steps-v1': RouteRecordInfo<'pages-authentication-two-steps-v1', '/pages/authentication/two-steps-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-two-steps-v2': RouteRecordInfo<'pages-authentication-two-steps-v2', '/pages/authentication/two-steps-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-verify-email-v1': RouteRecordInfo<'pages-authentication-verify-email-v1', '/pages/authentication/verify-email-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-verify-email-v2': RouteRecordInfo<'pages-authentication-verify-email-v2', '/pages/authentication/verify-email-v2', Record<never, never>, Record<never, never>>,
    'pages-faq': RouteRecordInfo<'pages-faq', '/pages/faq', Record<never, never>, Record<never, never>>,
    'pages-icons': RouteRecordInfo<'pages-icons', '/pages/icons', Record<never, never>, Record<never, never>>,
    'pages-misc-coming-soon': RouteRecordInfo<'pages-misc-coming-soon', '/pages/misc/coming-soon', Record<never, never>, Record<never, never>>,
    'pages-misc-under-maintenance': RouteRecordInfo<'pages-misc-under-maintenance', '/pages/misc/under-maintenance', Record<never, never>, Record<never, never>>,
    'pages-pricing': RouteRecordInfo<'pages-pricing', '/pages/pricing', Record<never, never>, Record<never, never>>,
    'pages-typography': RouteRecordInfo<'pages-typography', '/pages/typography', Record<never, never>, Record<never, never>>,
    'pages-user-profile-tab': RouteRecordInfo<'pages-user-profile-tab', '/pages/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'programs': RouteRecordInfo<'programs', '/programs', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'student-dashboard': RouteRecordInfo<'student-dashboard', '/student/dashboard', Record<never, never>, Record<never, never>>,
    'student-surveys': RouteRecordInfo<'student-surveys', '/student/surveys', Record<never, never>, Record<never, never>>,
    'student-surveys-id': RouteRecordInfo<'student-surveys-id', '/student/surveys-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'students': RouteRecordInfo<'students', '/students', Record<never, never>, Record<never, never>>,
    'surveys-parent': RouteRecordInfo<'surveys-parent', '/surveys', Record<never, never>, Record<never, never>>,
    'surveys': RouteRecordInfo<'surveys', '/surveys', Record<never, never>, Record<never, never>>,
    'surveys-id': RouteRecordInfo<'surveys-id', '/surveys/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'surveys-id-responses': RouteRecordInfo<'surveys-id-responses', '/surveys/:id-responses', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'surveys-dean-id': RouteRecordInfo<'surveys-dean-id', '/surveys/dean/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'surveys-dean-id-responses': RouteRecordInfo<'surveys-dean-id-responses', '/surveys/dean/:id-responses', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'surveys-random': RouteRecordInfo<'surveys-random', '/surveys/random', Record<never, never>, Record<never, never>>,
    'teachers': RouteRecordInfo<'teachers', '/teachers', Record<never, never>, Record<never, never>>,
  }
}
