/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'academic-terms': RouteRecordInfo<'academic-terms', '/academic-terms', Record<never, never>, Record<never, never>>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'class-sections': RouteRecordInfo<'class-sections', '/class-sections', Record<never, never>, Record<never, never>>,
    'classes': RouteRecordInfo<'classes', '/classes', Record<never, never>, Record<never, never>>,
    'classes-id': RouteRecordInfo<'classes-id', '/classes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'courses': RouteRecordInfo<'courses', '/courses', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'dean-dashboard': RouteRecordInfo<'dean-dashboard', '/dean/dashboard', Record<never, never>, Record<never, never>>,
    'dean-surveys': RouteRecordInfo<'dean-surveys', '/dean/surveys', Record<never, never>, Record<never, never>>,
    'dean-surveys-id': RouteRecordInfo<'dean-surveys-id', '/dean/surveys-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'departments': RouteRecordInfo<'departments', '/departments', Record<never, never>, Record<never, never>>,
    'departments-id': RouteRecordInfo<'departments-id', '/departments/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'landing': RouteRecordInfo<'landing', '/landing', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pages-account-settings-tab': RouteRecordInfo<'pages-account-settings-tab', '/pages/account-settings/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'pages-authentication-forgot-password-v1': RouteRecordInfo<'pages-authentication-forgot-password-v1', '/pages/authentication/forgot-password-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-forgot-password-v2': RouteRecordInfo<'pages-authentication-forgot-password-v2', '/pages/authentication/forgot-password-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v1': RouteRecordInfo<'pages-authentication-login-v1', '/pages/authentication/login-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-login-v2': RouteRecordInfo<'pages-authentication-login-v2', '/pages/authentication/login-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-multi-steps': RouteRecordInfo<'pages-authentication-register-multi-steps', '/pages/authentication/register-multi-steps', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-v1': RouteRecordInfo<'pages-authentication-register-v1', '/pages/authentication/register-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-register-v2': RouteRecordInfo<'pages-authentication-register-v2', '/pages/authentication/register-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-reset-password-v1': RouteRecordInfo<'pages-authentication-reset-password-v1', '/pages/authentication/reset-password-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-reset-password-v2': RouteRecordInfo<'pages-authentication-reset-password-v2', '/pages/authentication/reset-password-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-two-steps-v1': RouteRecordInfo<'pages-authentication-two-steps-v1', '/pages/authentication/two-steps-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-two-steps-v2': RouteRecordInfo<'pages-authentication-two-steps-v2', '/pages/authentication/two-steps-v2', Record<never, never>, Record<never, never>>,
    'pages-authentication-verify-email-v1': RouteRecordInfo<'pages-authentication-verify-email-v1', '/pages/authentication/verify-email-v1', Record<never, never>, Record<never, never>>,
    'pages-authentication-verify-email-v2': RouteRecordInfo<'pages-authentication-verify-email-v2', '/pages/authentication/verify-email-v2', Record<never, never>, Record<never, never>>,
    'pages-faq': RouteRecordInfo<'pages-faq', '/pages/faq', Record<never, never>, Record<never, never>>,
    'pages-icons': RouteRecordInfo<'pages-icons', '/pages/icons', Record<never, never>, Record<never, never>>,
    'pages-misc-coming-soon': RouteRecordInfo<'pages-misc-coming-soon', '/pages/misc/coming-soon', Record<never, never>, Record<never, never>>,
    'pages-misc-under-maintenance': RouteRecordInfo<'pages-misc-under-maintenance', '/pages/misc/under-maintenance', Record<never, never>, Record<never, never>>,
    'pages-pricing': RouteRecordInfo<'pages-pricing', '/pages/pricing', Record<never, never>, Record<never, never>>,
    'pages-typography': RouteRecordInfo<'pages-typography', '/pages/typography', Record<never, never>, Record<never, never>>,
    'pages-user-profile-tab': RouteRecordInfo<'pages-user-profile-tab', '/pages/user-profile/:tab', { tab: ParamValue<true> }, { tab: ParamValue<false> }>,
    'programs': RouteRecordInfo<'programs', '/programs', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'school-offices': RouteRecordInfo<'school-offices', '/school-offices', Record<never, never>, Record<never, never>>,
    'student-dashboard': RouteRecordInfo<'student-dashboard', '/student/dashboard', Record<never, never>, Record<never, never>>,
    'student-surveys': RouteRecordInfo<'student-surveys', '/student/surveys', Record<never, never>, Record<never, never>>,
    'student-surveys-id': RouteRecordInfo<'student-surveys-id', '/student/surveys-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'students': RouteRecordInfo<'students', '/students', Record<never, never>, Record<never, never>>,
    'surveys': RouteRecordInfo<'surveys', '/surveys', Record<never, never>, Record<never, never>>,
    'surveys-dean-evaluation': RouteRecordInfo<'surveys-dean-evaluation', '/surveys/dean-evaluation', Record<never, never>, Record<never, never>>,
    'surveys-dean-evaluation-id': RouteRecordInfo<'surveys-dean-evaluation-id', '/surveys/dean-evaluation/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'surveys-dean-evaluation-professor-survey-id-professor-id': RouteRecordInfo<'surveys-dean-evaluation-professor-survey-id-professor-id', '/surveys/dean-evaluation/professor-:surveyId-:professorId', { surveyId: ParamValue<true>, professorId: ParamValue<true> }, { surveyId: ParamValue<false>, professorId: ParamValue<false> }>,
    'surveys-student-evaluation': RouteRecordInfo<'surveys-student-evaluation', '/surveys/student-evaluation', Record<never, never>, Record<never, never>>,
    'surveys-student-evaluation-id': RouteRecordInfo<'surveys-student-evaluation-id', '/surveys/student-evaluation/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'surveys-student-evaluation-office-survey-id-office-id': RouteRecordInfo<'surveys-student-evaluation-office-survey-id-office-id', '/surveys/student-evaluation/office-:surveyId-:officeId', { surveyId: ParamValue<true>, officeId: ParamValue<true> }, { surveyId: ParamValue<false>, officeId: ParamValue<false> }>,
    'surveys-student-evaluation-professor-survey-id-professor-id': RouteRecordInfo<'surveys-student-evaluation-professor-survey-id-professor-id', '/surveys/student-evaluation/professor-:surveyId-:professorId', { surveyId: ParamValue<true>, professorId: ParamValue<true> }, { surveyId: ParamValue<false>, professorId: ParamValue<false> }>,
    'teachers': RouteRecordInfo<'teachers', '/teachers', Record<never, never>, Record<never, never>>,
  }
}
